name: Deployment CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    # - name: checkout
    #   uses: actions/checkout@v1

    # - name: Executing remote ssh commands using ssh key
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.HOST }}
    #     username: ${{ secrets.USERNAME }}
    #     key: ${{ secrets.KEY }}
    #     port: ${{ secrets.PORT }}
    #     passphrase: ${{ secrets.PASSPHRASE }}
    #     script: |
    #       sh ~/bin/deploy-test.sh

    # ls -al

    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/staging.key
        chmod 600 ~/.ssh/staging.key
        cat >>~/.ssh/config <<END
        Host staging
          HostName $SSH_HOST
          User $SSH_USER
          IdentityFile ~/.ssh/staging.key
          StrictHostKeyChecking no
        END
      env:
        SSH_USER: ${{ secrets.USERNAME }}
        SSH_KEY: ${{ secrets.KEY }}
        SSH_HOST: ${{ secrets.HOST }}
    
    - name: Running deploy command
      run: ssh -t staging 'sh ~/bin/deploy-test.sh'